//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CthulhuPlayerCard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Projekt_CthulhuEntities : DbContext
    {
        public Projekt_CthulhuEntities()
            : base("name=Projekt_CthulhuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Imiona> Imiona { get; set; }
        public virtual DbSet<Nazwiska> Nazwiska { get; set; }
        public virtual DbSet<Rzeczy_osobiste> Rzeczy_osobiste { get; set; }
        public virtual DbSet<Spis_postaci> Spis_postaci { get; set; }
        public virtual DbSet<Typy_przedmiotów> Typy_przedmiotów { get; set; }
        public virtual DbSet<Zawody> Zawody { get; set; }
    }
}
