//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CthulhuPlayerCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nazwiska
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nazwiska()
        {
            this.Spis_postaci = new HashSet<Spis_postaci>();
        }
    
        public int Id_nazwiska { get; set; }
        public string Nazwisko { get; set; }
        public string Pochodzenie_nazwiska { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spis_postaci> Spis_postaci { get; set; }
    }
}
