//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CthulhuPlayerCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spis_postaci
    {
        public int Id_postaci { get; set; }
        public int Id_imienia { get; set; }
        public int Id_nazwiska { get; set; }
        public short Wiek { get; set; }
        public int Id_zawodu { get; set; }
        public string Plec { get; set; }
        public string Miejsce_zamieszkania { get; set; }
        public string Pochodzenie { get; set; }
        public Nullable<short> Sila { get; set; }
        public Nullable<short> Zrecznosc { get; set; }
        public Nullable<short> Kondycja { get; set; }
        public Nullable<short> Wyglad { get; set; }
        public Nullable<short> Wyksztalcenie { get; set; }
        public Nullable<short> Budowa_ciala { get; set; }
        public Nullable<short> Inteligencja { get; set; }
        public Nullable<byte> Szczescie { get; set; }
        public Nullable<short> Moc { get; set; }
        public Nullable<int> Id_przedmiotu { get; set; }
        public Nullable<byte> Historia { get; set; }
        public Nullable<byte> Bijatyka { get; set; }
        public Nullable<byte> Spostrzegawczosc { get; set; }
        public Nullable<byte> Pierwsza_Pomoc { get; set; }
        public Nullable<byte> Bron_Palna { get; set; }
    
        public virtual Imiona Imiona { get; set; }
        public virtual Nazwiska Nazwiska { get; set; }
        public virtual Rzeczy_osobiste Rzeczy_osobiste { get; set; }
        public virtual Zawody Zawody { get; set; }
    }
}
