//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CthulhuPlayerCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Typy_przedmiotów
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Typy_przedmiotów()
        {
            this.Rzeczy_osobiste = new HashSet<Rzeczy_osobiste>();
        }
    
        public short Id_typu { get; set; }
        public string Nazwa_typu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rzeczy_osobiste> Rzeczy_osobiste { get; set; }
    }
}
