create view ListaPrzedmiotow as
select Spis_postaci.Id_postaci, Rzeczy_osobiste.Nazwa_przedmiotu, Typy_przedmiotow.Nazwa_typu, Typy_przedmiotow.Id_typu
From Spis_postaci
Join Rzeczy_osobiste on Spis_postaci.Id_przedmiotu=Rzeczy_osobiste.Id_przedmiotu
Join Typy_przedmiotow on Rzeczy_osobiste.Id_typu=Typy_przedmiotow.Id_typu