//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CthulhuPlayerCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zawody()
        {
            this.Spis_postaci = new HashSet<Spis_postaci>();
        }
    
        public int Id_zawodu { get; set; }
        public string Nazwa_zawodu { get; set; }
        public string Zwiazana_Historia { get; set; }
        public string Zwiazana_Bijatyka { get; set; }
        public string Zwiazana_Spostrzegawczosc { get; set; }
        public string Zwiazana_Pierwsza_Pomoc { get; set; }
        public string Zwiazana_Bron_Palna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spis_postaci> Spis_postaci { get; set; }
    }
}
